### ISSUE TITLE
StructureMoleculeComponent and Mobile Devices

### ISSUE THREAD

**Issue by lantunes** [materialsproject/crystaltoolkit#346] opened 2023-06-16 12:25 UTC
The `StructureMoleculeComponent` renders on mobile devices, but I'm unable to rotate the structure in the viewer. I can only zoom in and out on the structure. The viewer's buttons (e.g. settings, export) work normally. I've encountered this on a Pixel 4a and iPhone 8, using a Chrome browser.

**Comment by janosh** [comment] 2023-06-16 13:57
You have to swipe across with 2 fingers to rotate. I just tried it out on iPhone 14 and it's admittedly quite hard to control but that seems to be the intended behavior.

**Comment by janosh** [comment] 2023-06-20 21:47
Closing as closed. Feel free to ping back if you think the current behavior needs changing.

**Closed by janosh** 2023-06-20 21:47 UTC
